export const ACTIONS = {
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    CREATE: 'CREATE',
    GET: 'GET',
    RECEIVE_INVENTORY: 'RECEIVE_INVENTORY',
    VIEW_INVENTORY: 'VIEW_INVENTORY',
    DISPATCH_INVENTORY: 'DISPATCH_INVENTORY',
}

export const TARGET_TYPES = {
    USER: "USER",
    WAREHOUSE: "WAREHOUSE",
    ROLE: "ROLE",
    PERMISSION: "PERMISSION",
    INVENTORY: "INVENTORY",
}

export const OUTCOMES = {
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
}

export const LOGIN_STATUS = {
    LOCKED: 'LOCKED',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
}

export const NOTIFICATION_TYPE = {
    ASSIGNMENT: "ASSIGNMENT",
}

export const NOTIFICATION_TARGET_ROLE = {
    ENGINEER: "ENGINEER",
}

export const MAX_LOGIN_ATTEMPTS = 5;

export const LOCK_TIME = 15 * 60 * 1000;

export default {
    ACTIONS,
    TARGET_TYPES,
    OUTCOMES,
    LOGIN_STATUS,
    MAX_LOGIN_ATTEMPTS,
    LOCK_TIME
};