import mongoose from "mongoose";

const variantSchema = new mongoose.Schema(
  {
    // _id is auto-generated by mongoose for subdocs.
    // We expose it as `_idVariants` via the toJSON transform below
    // and place it FIRST so the frontend can address a variant by id.
    color: {
      type: String,
      required: [true, "Color is required!"],
      trim: true,
    },
    size: {
      type: String,
      trim: true,
    },
    hexCode: {
      type: String,
      required: [true, "Hex code is required!"],
      trim: true,
    },
    price: {
      type: Number,
      required: [true, "Price is required!"],
    },
    stock: {
      type: Number,
      required: true,
      default: 0,
    },
    image: {
      type: String,
      required: [true, "Variant image is required!"],
      trim: true,
    },
  },
  { _id: true },
);

const productSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "Product name is required!"],
      trim: true,
    },
    description: {
      type: String,
      required: [true, "Description is required!"],
    },
    category: {
      type: String,
      enum: ["yarn", "hook", "needle", "accessory", "kit"],
      required: [true, "Category is required!"],
    },
    image: {
      type: String,
      required: [true, "Image is required!"],
    },
    // `images` field has been removed. Each variant now carries its own
    // `image` field. We still strip any legacy `images` value via the
    // toJSON transform below for backward compatibility with old docs.
    tags: [
      {
        type: String,
      },
    ],
    variants: {
      type: [variantSchema],
      required: [true, "At least one variant is required!"],
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
    id: true, // enable `id` virtual (string version of `_id`)
    toJSON: { transform: transformProduct, virtuals: true },
    toObject: { transform: transformProduct, virtuals: true },
  },
);

/**
 * Transform the document so that:
 *  - The legacy `images` field (if somehow still present) is dropped.
 *  - The product's `_id` and `id` are placed FIRST (in that order) in
 *    the JSON output for easy access by the frontend.
 *  - Each variant's `_id` is exposed as `_idVariants` and placed FIRST.
 *  - Each variant's `image` is placed second (right after `_idVariants`).
 */
function transformProduct(_doc, ret) {
  if (ret && Object.prototype.hasOwnProperty.call(ret, "images")) {
    delete ret.images;
  }

  if (Array.isArray(ret && ret.variants)) {
    ret.variants = ret.variants.map(reorderVariant);
  }

  // Reorder product-level fields so `_id` and `id` come first
  if (ret && typeof ret === "object") {
    const { _id, id, ...rest } = ret;
    const ordered = {};
    if (_id !== undefined) ordered._id = String(_id);

    for (const key of Object.keys(rest)) {
      if (key === "_id" || key === "id") continue;
      ordered[key] = rest[key];
    }
    return ordered;
  }

  return ret;
}

function reorderVariant(variant) {
  if (!variant || typeof variant !== "object") return variant;

  const { _id, ...rest } = variant;
  const _idVariants = _id ? String(_id) : undefined;
  const { image, ...restWithoutImage } = rest;

  const ordered = {};
  if (_idVariants !== undefined) ordered._idVariants = _idVariants;
  if (image !== undefined) ordered.image = image;
  for (const key of Object.keys(restWithoutImage)) {
    ordered[key] = restWithoutImage[key];
  }
  return ordered;
}

const Product = mongoose.model("Product", productSchema, "products");
export default Product;
